# Generated by Django 5.0.3 on 2024-07-18 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("license", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="license",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_sessions",
                to="license.license",
                verbose_name="License",
            ),
            preserve_default=False,
        ),
    ]
